
[build]
  command = "echo 'Skipping build'"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
