
[build]
  command = "node netlify-build.js"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
